name: Check for Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: install
        run: yarn
      - name: format-check
        run: yarn format-check
      - name: lint
        run: yarn lint
      - name: type-check
        run: yarn type-check
      - name: build
        run: yarn build
