name: Check for Pull Request

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - .github/**/*
      - .husky/**/*
      - .vscode/**/*

jobs:
  format-check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: install
        run: yarn
      - name: format-check
        run: yarn format-check

  lint-check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: install
        run: yarn
      - name: lint
        run: yarn lint

  type-check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: install
        run: yarn
      - name: type-check
        run: yarn type-check

  build-check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: cache gatsby build
        uses: actions/cache@v2
        id: gatsby-cache-build
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-
      - name: install
        run: yarn
      - name: build
        run: yarn build --log-pages
        env:
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
